FROM ghcr.io/coveooss/tgf:${GIT_TAG}-base
LABEL tgf-image-tag=""

ARG EXE_FOLDER=/usr/local/bin
ARG TARGETPLATFORM

ENV TGF_IMAGE_TAG=""

# Install tools
RUN apk add --no-cache python3 groff less tree py3-pip bash zsh fish bash-completion jq zip nano vim git

# Update pip to the latest version and install pipx (Python )
RUN pip3 install --no-cache-dir --upgrade pip pipx

# Install the AWS CLI
ENV PATH="/root/.local/bin:${PATH}"
RUN pipx install --pip-args='--no-cache-dir' awscli

RUN if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi

# Update version here (do not move at the beginning of the file since it would slow down the docker build)
ENV TF_LINT_VERSION="0.30.0"
ENV TF_DOC_VERSION="0.10.13"

COPY Dockerfile.1_scripts/download_executables.sh .
RUN chmod +x ./download_executables.sh
RUN ./download_executables.sh
