name: Build
on:
  pull_request: {}
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # https://github.com/docker/buildx/issues/729#issuecomment-898929143
      - name: Prepare Docker build
        run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build and push PR images for testing
        if: ${{ github.event_name == "pull_request" }}
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
        run: python ./build_and_push_images.py --version "v0.0.PR-$PR_NUMBER"

      - name: Build and push release images
        if: ${{ github.event_name == "tag" }}
        env:
          VERSION: ${{ github.ref_name }}
        run: python ./build_and_push_images.py --version "$VERSION"
