name: Build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # https://github.com/docker/buildx/issues/729#issuecomment-898929143
      - name: Prepare Docker build
        run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build and Push Images
        run: python ./build_images.py --push
