name: CI
on: pull_request

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:stable

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Install system dependencies
        run: |
          apk add --no-cache \
            git \
            fd

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Run shellcheck
        run: fd --hidden --exclude .git . -e .sh -x shellcheck --color=always

  build-and-push-test-images:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Build and push test images
        uses: ./.github/actions/build-and-push-images
        with:
          version: v0.0.PR-${{ github.event.number }}
